<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sources\Modules\Loggers\Serilog\LogMQ.Loggers.Serilog\LogMQ.Loggers.Serilog.csproj" />
    <ProjectReference Include="..\..\..\Sources\Modules\Providers\LogMQ.Providers.Msmq\LogMQ.Providers.Msmq.csproj" />
    <ProjectReference Include="..\..\..\Sources\Modules\Providers\LogMQ.Providers.Tcp\LogMQ.Providers.Tcp.csproj" />
  </ItemGroup>

</Project>
