<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Broker\Plugins\Storage\LogMQ.Storage.RocksDb\LogMQ.Storage.RocksDb.csproj" />
    <ProjectReference Include="..\..\Shared\LogMQ.Services.Shared.LogManager\LogMQ.Services.Shared.LogManager.csproj" />
  </ItemGroup>

</Project>
