<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>LogMQ.Plugins.Receivers</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\LogMQ.Packages.Providers.Tcp\LogMQ.Providers.Tcp.csproj" />
		<ProjectReference Include="..\LogMQ.Plugins.ReceiverContracts\LogMQ.Plugins.ReceiverContracts.csproj" />
	</ItemGroup>

</Project>
