<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-LogMQ.Services.Broker-2222fde6-509c-40e8-80ea-d71f28b38ff3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.2.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.3" />
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.2.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\LogMQ.Services.Shared.Common\LogMQ.Services.Shared.Common.csproj" />
    <ProjectReference Include="..\..\Shared\LogMQ.Services.Shared.LogManager\LogMQ.Services.Shared.LogManager.csproj" />
    <ProjectReference Include="..\Plugins\Receivers\Contracts\LogMQ.Receivers.Contracts\LogMQ.Receivers.Contracts.csproj" />
    <ProjectReference Include="..\Plugins\Receivers\LogMQ.Receivers.Msmq\LogMQ.Receivers.Msmq.csproj" />
    <ProjectReference Include="..\Plugins\Receivers\LogMQ.Receivers.Tcp\LogMQ.Receivers.Tcp.csproj" />
  </ItemGroup>
</Project>
